### ISSUE TITLE
zero  infinity

### ISSUE THREAD

**Issue by as-hirose** [AlvaroAsial/JapaneseLearning#11]
https://github.com/AlvaroAsial/JapaneseLearning/blob/b9ec51ef1fb9660f579a72c1da4853e5b072846f/src/Main.js#L52

There is no possibility that `unlockedCount.values[0].count` is zero? (zero  infinity)

**Comment by AlvaroAsial** [comment]
There is no possibility, since the user starts always with 5 unlocked levels.
